E_Commerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy
from django.contrib.auth import login
from main import views as m_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('home/', m_views.HomePageView.as_view(), name='home'),
                  path('clothing/', m_views.MainPageView.as_view(), name='main'),
                  path('clothing/<int:pk>', m_views.ProductDetailView.as_view(), name='product-detail'),
                  path('clothing/add', m_views.ProductCreateView.as_view(), name='add-clothing'),
                  path('basket/save/', m_views.SaveToBasketView.as_view(), name='basket'),
                  path('basket/', m_views.BasketPageView.as_view(), name='view-basket'),
                  path('api/test/', m_views.TestApiView.as_view(), name='test-api'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django_common.auth_backends import User


class Product(models.Model):
    product_name = models.CharField(blank=False, null=False, max_length=75)
    PRODUCT_TYPES = (
        ('Top', 'Top'),
        ('Bottom', 'Bottom'),
    )
    product_type = models.CharField(choices=PRODUCT_TYPES, max_length=256, blank=False, null=False)
    price = models.PositiveIntegerField(verbose_name='Price (£) ')
    description = models.CharField(blank=False, null=False, max_length=256)
    thumbnail = models.ImageField(upload_to='main/images/', help_text='This will be the thumbnail shown to customers')


def get_image_filename(instance, filename):
    title = instance.product.product_name
    slug = slugify(title)
    return "main/images/{}-{}".format(slug, filename)


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to=get_image_filename,
                                 verbose_name='Picture', help_text='This will be displayed on the product page')

main/forms.py
from django import forms
from django.forms import formset_factory

from main.models import Image, Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'product_type', 'price', 'thumbnail', 'description']


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['picture']


ImageFormset = formset_factory(ImageForm, extra=4, max_num=4, min_num=1)

main/views.py
from django.contrib.auth.forms import UserCreationForm
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, FormView, CreateView, ListView, UpdateView, DeleteView, DetailView
import praw

# Create your views here.
from django_common.auth_backends import User

# Create your views here.
from main.forms import ImageFormset, ProductForm
from main.models import Product


class HomePageView(TemplateView):
    template_name = 'main/home_page.html'


class MainPageView(ListView):
    model = Product
    paginate_by = 10
    template_name = 'main/main_page.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        categories_info = {}
        categories_info['types'] = []
        categories_info['amounts'] = []

        product_types = ['Top', 'Bottom']

        for product_type in product_types:
            categories_info['types'].append(product_type)
            categories_info['amounts'].append(Product.objects.filter(product_type=product_type).count())
        json_response = json.dumps(categories_info)
        context['jsonResponse'] = json_response
        context['filters'] = self.request.GET.getlist('filter')
        return context

    def get_queryset(self):
        order_by = self.request.GET.get('order_by')
        # List of strings of filter parameters
        filters = self.request.GET.getlist('filter')
        if order_by:
            if order_by == 'pricedesc':
                if filters:
                    return Product.objects.all().order_by('-price').filter(product_type__in=filters)
                else:
                    return Product.objects.all().order_by('-price')

            elif order_by == 'priceascend':
                if filters:
                    return Product.objects.all().order_by('price').filter(product_type__in=filters)
                else:
                    return Product.objects.all().order_by('price')
        elif filters:
            return Product.objects.all().filter(product_type__in=filters)
        else:
            return super().get_queryset()


class ProductCreateView(View):
    template_name = 'main/create_product.html'
    success_url = reverse_lazy('add-clothing')

    def get(self, request):
        context = {'image_formset': ImageFormset, 'form': ProductForm}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        # Forms
        product_form = ProductForm(request.POST, request.FILES)
        image_formset = ImageFormset(request.POST, request.FILES)

        if product_form.is_valid() and image_formset.is_valid():
            product_instance = product_form.save(commit=False)
            product_instance.save()
            for form in image_formset:
                # Only save if an image has been provided
                if form.cleaned_data.get('picture'):
                    image_instance = form.save(commit=False)
                    image_instance.product = product_instance
                    image_instance.save()
            return HttpResponseRedirect(self.success_url)
        else:
            context = {'image_formset': ImageFormset(self.request.POST), 'form': ProductForm(self.request.POST)}
            return render(self.request, self.template_name, context)


class ProductDetailView(DetailView):
    model = Product
    fields = ['product_name', 'product_type', 'price', 'description']
    template_name = 'main/product_page.html'


class BasketPageView(TemplateView):
    template_name = 'main/basket_page.html'
    paginate = 10
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['products'] = []
        # Get products from basket
        for product_id, product_amount in self.request.session['basket'].items():
            # Append a dictionary so indexing the html file is clearer
            context['products'].append(
                {'product': Product.objects.get(pk=int(product_id)), 'product_amount': product_amount})
        return context


class SaveToBasketView(View):

    def get(self, request):
        return JsonResponse(request.session['basket'])

    def post(self, request):
        # Post method to save items to a basket in the request session
        body_unicode = request.body.decode('utf-8')
        body = json.loads(body_unicode)
        # Int version of product_id
        product_id = str(body['productId'])
        if 'basket' in request.session and product_id in request.session['basket']:
            request.session['basket'][product_id] += 1
        else:
            request.session['basket'] = {product_id: 1}
        print(request.session['basket'])
        return HttpResponse(status=200)


class TestApiView(View):

    def get(self, request):
        print('getting json')
        data = {'student_id': 3}
        return JsonResponse(data)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css"
          integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css"
          integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    {% block custom_css %}
        <link href="{% static "main/css/style.css" %}" rel="stylesheet">
    {% endblock %}
    <script src="{% static "main/js/main.js" %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>
<body>
{% include 'main/nav_bar.html' %}
{% block content %}
{% endblock %}

{% include 'main/footer.html' %}

{% block document_ready_script %}
{% endblock %}

</body>
</html>

main/templates/main/basket_page.html
{% extends 'main/base.html' %}

{% block title %}
    Shopping Bag
{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 80px;">
        {% for product_tuple in products %}
            {{ product_tuple.product.product_name }}
            {{ product_tuple.product_amount }}
        {% endfor %}
    </div>
{% endblock %}

{% block document_ready_script %}
    <script>
        basketPage();
    </script>
{% endblock %}

main/templates/main/create_product.html
{% extends 'main/base.html' %}
{% block title %}
    Add Clothing
{% endblock %}

{% block content %}
    <div class="container reset-top-page">
        <h3><u>Add Product</u></h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'main/generic_form_template.html' with form=form %}
            {% include 'main/generic_formset_template.html' with formset=image_formset show=1 have_is_valid=0 %}
            <div id="app">
                {% verbatim %}
                <button type="button" @click="removePicture" :disabled="disableRemoveButton"  class="btn btn-danger">Remove Picture</button>
                <button type="button" @click="showPicture" :disabled="disableAddButton" class="btn btn-success">Add Picture</button>
                <button style="float:right;" type="submit" class="btn btn-primary">Submit</button>
                <p class="text-muted" style="font-size: 13px;" v-if="disableRemoveButton">You must have at least one picture to display</p>
                <p class="text-muted" style="font-size: 13px;" v-if="disableAddButton">You can only add a maximum of 4 images</p>
                {% endverbatim %}
            </div>
        </form>
    </div>
{% endblock %}
{% block document_ready_script %}
    <script>
        addPage();
    </script>
{% endblock %}

main/templates/main/footer.html
<div class="above-footer">
    <a href="#"><i style="color: #86513f" class="social-icon fab fa-instagram"></i></a>
    <a href="#"><i style="color: #4267b2" class="social-icon fab fa-facebook"></i></a>
    <a href="#"><i style="color: #fffc00;" class="social-icon fab fa-snapchat"></i></a>
</div>
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="mt-5">
                    <h6 class="footer-title">CONTACT</h6>
                </div>
                <a href="#" class="footer-item">Message Us</a>
                <a href="#" class="footer-item">Give us a ring</a>
            </div>
            <div class="col">
                <div class="mt-5">
                    <div class="mt-5">
                        <h6 class="footer-title">ABOUT</h6>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="mt-5">
                    <h6 class="footer-title">HELP AND INFORMATION</h6>
                </div>
            </div>
        </div>
    </div>
</div>

main/templates/main/generic_form_template.html
{% load widget_tweaks %}

{#<form method="post" {% if image_field_used %}enctype="multipart/form-data"{% endif %}>#}
{#    {% csrf_token %}#}

    {% for hidden_field in form.hidden_fields %}
        {{ hidden_field }}
    {% endfor %}

    {% if form.non_field_errors %}
        <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}

    {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }}

            {% if form.is_bound %}
                {% if field.errors %}
                    {% render_field field class="form-control is-invalid" %}
                    {% for error in field.errors %}
                        <div class="invalid-feedback">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% render_field field class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field field class="form-control" %}
            {% endif %}

            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
        </div>
    {% endfor %}

{#{% if not_remove_submit %}#}
{#    <button type="submit" class="btn btn-primary">Submit</button>#}
{#{% endif %}#}
{#</form>#}

main/templates/main/generic_formset_template.html
{% load widget_tweaks %}

{% if formset.non_form_errors %}
    <div class="alert alert-danger" role="alert">
        {% for error in formset.non_form_errors %}
            {{ error }}
        {% endfor %}
    </div>
{% endif %}

{% if show %}
    {% for form in formset %}
        <div class="formset-group" {% if forloop.counter > show %} style="display:none"{% endif %}>
            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}

            {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}

            {% for field in form.visible_fields %}
                <div class="form-group">
                    {{ field.label_tag }}

                    {% if form.is_bound %}
                        {% if field.errors %}
                            {% render_field field class="form-control is-invalid" %}
                            {% for error in field.errors %}
                                <div class="invalid-feedback">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        {% else %}
                            {% if have_is_valid %}
                                {% render_field field class="form-control is-valid" %}
                            {% else %}
                                {% render_field field class="form-control" %}
                            {% endif %}
                        {% endif %}
                    {% else %}
                        {% render_field field class="form-control" %}
                    {% endif %}

                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endfor %}

{% else %}
    {% for form in formset %}
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}

                {% if form.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control" %}
                {% endif %}

                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}
{{ formset.management_form }}

main/templates/main/generic_main_page.html
{% extends 'main/base.html' %}
{##}
{#{% block title %}#}
{#    Clothing#}
{#{% endblock %}#}

{% block content %}
    <div class="main-page-header"><h1 style="font-size:24px;font-weight:bold;">{% block header %}{% endblock %}</h1>
    </div>
    <div style="" id="app">
        {% load custom_filters %}
        <category-search-bar categories="{{ jsonResponse }}" sorted_selection="{{ request.GET.order_by }}"
                             num_tops="3"
                             filter_selection="{{ request.GET|get_list:'filter' }}"
                             num_bottoms="4"></category-search-bar>
    </div>
    {% block main %}
    {% endblock %}

{% endblock %}

main/templates/main/home_page.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="text-block-container">
        <img height="100%" width="100%" src="{% static 'main/images/background-placeholder.jpg' %}">
        <div class="text-block typewriter">
            <h1>Welcome</h1>
            <p class="typewriter" style="font-size:15px;">To Parrot Clothing</p>
        </div>
    </div>
{% endblock %}

{% block document_ready_script %}
    <script>
        homepage();
    </script>
{% endblock %}

main/templates/main/main_page.html
{% extends 'main/generic_main_page.html' %}

{% block title %}
    Clothing
{% endblock %}

{% block header %}
    New Items
{% endblock %}

{% block main %}
    {#    product-list is used for vue marker#}
    <div id="product-list">
        {% for product in product_list %}
            <product page_url="{% url 'product-detail' pk=product.pk %}" class="product mr-2"
                     source="{{ product.thumbnail.url }}" price="{{ product.price }}"
                     title="{{ product.product_name }}"></product>
        {% endfor %}
    </div>

{% endblock %}

{% block document_ready_script %}
    <script>
        mainPage();
    </script>
{% endblock %}

main/templates/main/nav_bar.html
<div class="nav-bars-wrapper" id="navbar-app">

    <nav class="main-navbar show-bottom-border">
        {#        <a id="navbar-brand" href="#" class="nav-bar-item">Parrot Clothing</a>#}
        <a id="navbar-brand" href="{% url 'home' %}" class="nav-bar-item"><span>Pa</span><span
                style="color: red;">r</span><span
                style="color:orange">r</span>o<span style="color: green">t</span> <span style="color: orange">C</span>lo<span
                style="color:red;">t</span><span style="color: green">h</span>in<span style="color:orange">g</span></a>
        <div class="nav-bar-item nav-bar-tab">HOME</div>

        <span style="margin-left: auto;" class="search-bar-wrapper">
    <input id="nav-bar-search-bar" type="text" placeholder="Search...">
    <button id="search-icon"><i class="fas fa-search"></i></button>
    </span>
       <a href="{% url 'view-basket' %}"><i id="shopping-basket" class="fas fa-shopping-basket"></i></a>
    </nav>
    <nav class="secondary-navbar display-none">
        <button data-url="{% url 'main' %}" class="ml-5 second-navbar-item" type="button">Clothing</button>
        <button data-url="{% url 'add-clothing' %}" class="second-navbar-item" type="button">Add Product</button>
    </nav>
</div>

<script>
    navBar();
</script>

main/templates/main/product_page.html
{% extends 'main/base.html' %}

{% block title %}
    {{ object.product_name }}
{% endblock %}

{% block content %}
    <div class="container" style="margin-top:80px; margin-bottom: 20px;max-width: 940px;" id="app">
        {#        <h1>This is a placeholder</h1>#}
        <div class="row">
            <div class="col-1">
                {% for image in object.image_set.all %}
                    <img {% verbatim %}@click="setMainImage" {% endverbatim %} class="product-image"
                         data-src="{{ image.picture.url }}"
                         style="{% if not forloop.first %}margin-top: 8px;{% endif %}margin-bottom:8px;" height="54"
                         width="43" src="{{ image.picture.url }}">
                {% endfor %}
            </div>
            <div class="col-6">
                {% for image in object.image_set.all %}
                    {% if forloop.first %}
                        <img id="main-image" height="650" width="512" src="{{ image.picture.url }}">
                        <button @click="leftImageButton" class="left-image-button" type="button"><i
                                class="arrow fas fa-chevron-left"></i></button>
                        <button @click="rightImageButton" class="right-image-button" type="button"><i
                                class="arrow fas fa-chevron-right"></i></button>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="product-page-right-column col-5">
                <div class="row">
                    <h1>{{ object.product_name }}</h1>
                </div>
                <div class="row">
                    <span class="product-price">£{{ object.price }}</span>
                </div>
                <div class="row my-2">
                    {{ object.description }}
                </div>
                <div class="row mt-3">
                    <button @click="addItemToBasket({{ object.pk }})" type="button" class="add-to-basket btn btn-success">ADD TO BASKET</button>
                </div>
            </div>
        </div>
    </div>
    <div id="post-url" data-url="{% url 'basket' %}"></div>
    {% csrf_token %}
{% endblock %}

{% block document_ready_script %}
    <script>
        productPage();
    </script>
{% endblock %}

main/templates/main/test_page.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="typewriter">
        <h1>The cat and the hat.</h1>
    </div>
{% endblock %}

{% block document_ready_script %}
    <script>
    </script>
{% endblock %}